@IReadThis.Recommender_HostAddress = http://localhost:5179

GET {{IReadThis.Recommender_HostAddress}}/BookCatalog/
Accept: application/json

###

GET {{IReadThis.Recommender_HostAddress}}/Recommendation/
Accept: application/json

###

POST {{IReadThis.Recommender_HostAddress}}/Admin/
Content-Type: application/json